In [1]:
# Useful additional packages
import qiskit
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

q = QuantumRegister(1)

In [2]:
qc = QuantumCircuit(q)
qc.u3(pi/2,pi/2,pi/2,q)  # initialize u gate, allows superpositions
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   ,  0.   -0.707j],
       [ 0.   +0.707j, -0.707+0.j   ]])

In [3]:
qc = QuantumCircuit(q)
qc.u0(pi/2,q)
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.iden(q)   # initialize identity gate
qc.draw(output='mpl')

job = execute(qc, backend)   # need to execute job before outputting 
job.result().get_unitary(qc, decimals=3)    # parts of array in numpy.ndarray

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [4]:
qc = QuantumCircuit(q)
qc.x(q)    # call x-gate on circuit (not, bit flip)
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.y(q)   # call y-gate on circuit (bit- and phase-flip)
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.z(q)   # call z-gate on circuit (phase flip)
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)



array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [5]:
qc = QuantumCircuit(q)
qc.h(q)    # calls Hadamard gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.s(q)    # calls S gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [6]:
qc = QuantumCircuit(q)
qc.sdg(q)   # calls S+ gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.t(q)    # calls a T gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.tdg(q)   # calls a T+ gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.rx(pi/2,q)   # calls x-rotation gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

qc = QuantumCircuit(q)
qc.ry(pi/2,q)   # calls y-rotation gate on circuit
qc.draw(output='mpl')

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j, -0.707+0.j],
       [ 0.707+0.j,  0.707+0.j]])